Models/ErrorViewModel.cs
using System;

namespace HouseShop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/House/HouseListItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HouseShop.Models.House
{
    public class HouseListItem
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public int Size { get; set; }
        public string Condition { get; set; }
        public DateTime CreatedAT { get; set; }
        public DateTime ModifiedAT { get; set; }

    }
}

Models/House/HouseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HouseShop.Models.House
{
    public class HouseViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public int Size { get; set; }
        public string Condition { get; set; }
        public DateTime CreatedAT { get; set; }
        public DateTime ModifiedAT { get; set; }
    }
}

Controllers/HomeController.cs
using HouseShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HouseShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HouseController.cs
using HouseShop.Core.Dto;
using HouseShop.Core.ServiceInterface;
using HouseShop.Data;
using HouseShop.Models.House;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace House.Controllers
{
    public class HouseController : Controller
    {
        private readonly HouseDbContext _context;
        private readonly IHouseService _houseService;

        public HouseController
            (
            HouseDbContext context,
            IHouseService houseService

            )
        {
            _context = context;
            _houseService = houseService;

        }

        //ListItem
        [HttpGet]
        public IActionResult Index()
        {
            var result = _context.House
                .OrderByDescending(y => y.CreatedAT)
                .Select(x => new HouseListItem
                {
                    Id = x.Id,
                    Name = x.Name,
                    Description = x.Description,
                    Address = x.Address,
                    Size = x.Size,
                    Condition = x.Condition,
                    
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Add()
        {
            HouseViewModel model = new HouseViewModel();

            return View("Edit", model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(HouseViewModel model)
        {
            var dto = new HouseDto()
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Address = model.Address,
                Size = model.Size,
                Condition = model.Condition,
                CreatedAT = model.CreatedAT,
                ModifiedAT = model.ModifiedAT,

            };

            var result = await _houseService.Add(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var house = await _houseService.Delete(id);
            if (house == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var house = await _houseService.GetAsync(id);

            if (house == null)
            {
                return NotFound();
            }

            var model = new HouseViewModel();

            model.Id = house.Id;
            model.Name = house.Name;
            model.Description = house.Description;
            model.Address = house.Address;
            model.Size = house.Size;
            model.Condition = house.Condition;
            model.ModifiedAT = house.ModifiedAT;
            model.CreatedAT = house.CreatedAT;


            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(HouseViewModel model)
        {
            var dto = new HouseDto()
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Address = model.Address,
                Size = model.Size,
                Condition = model.Condition,
                CreatedAT = model.CreatedAT,
                ModifiedAT = model.ModifiedAT,

            };

            var result = await _houseService.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), model);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/House/Edit.cshtml
@model HouseShop.Models.House.HouseViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Add</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAT" type="hidden" />
        <input asp-for="ModifiedAT" type="hidden" />

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" />
            </div>
        </div>


        <div class="form-group row">
            <label asp-for="Description" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Description" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Address" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Size" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Size" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Condition" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Condition" class="form-control" />
            </div>
        </div>



        @if (Model.Id.HasValue)
        {
            <input asp-action="edit" asp-controller="house" type="submit" class="btn btn-primary" value="Update">
            <input asp-action="delete" asp-controller="house" asp-for="Id" type="submit" class="btn btn-danger" value="Delete">
        }
        else
        {
            <input asp-action="add" asp-controller="house" type="submit" class="btn btn-primary" value="Add">
        }
        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>

Views/House/Index.cshtml
@model IEnumerable<HouseShop.Models.House.HouseListItem>

@{
    int queueNumber = 0;
}

<div class="h1">
    House
</div>

<div class="">
    <a asp-action="add" asp-controller="house" type="submit" class="btn btn-primary">Add</a>
</div>
<form method="post" class="m-1">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Address</th>
                <th scope="col">Size</th>
                <th scope="col">Condition</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var house in Model)
            {
                queueNumber += 1;

                <tr>
                    <th scope="row">@queueNumber</th>
                    <td class="">@house.Name</td>
                    <td class="">@house.Description</td>
                    <td class="">@house.Address</td>
                    <td class="">@house.Size</td>
                    <td class="">@house.Condition</td>
                    <td class="">
                        <a asp-action="edit" asp-controller="house" asp-route-id="@house.Id" class="btn btn-primary">Edit</a>
                        <input asp-action="delete" asp-controller="house" asp-route-id="@house.Id" type="submit" class="btn btn-danger" value="Delete">
                    </td>
                </tr>
            }
        </tbody>

    </table>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HouseShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HouseShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Index">House</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HouseShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>